version: '2.1'
#Note the .env file with variables

services:
    gs:
        build: 
           context: ./geoserver
           args:
               ORACLE_JDK: "true"
               TOMCAT_EXTRAS: "false"
        links:
            - postgis:postgis 
        container_name: geoserver
        depends_on:
            postgis:
              condition: service_healthy 
        #ports:
        #    - "80:8080"
        networks:
             vpcbr:
                ipv4_address: ${IP_GS}
    postgis:
        build:
           context: ./postgis
        environment:
           ALLOW_IP_RANGE: $SUBNET
        healthcheck:
            test: ["CMD", "nc", "-zv", "localhost", "5432"]
            interval: 30s
            timeout: 10s
            retries: 5
        container_name: postgis
        networks:
             vpcbr:
                ipv4_address: $IP_PG
    etf:
       build:
           context: ./etf-webapp
       container_name: etf-webapp
       volumes:
           - etf_vol:/etf
       networks:
           vpcbr:
                ipv4_address: $IP_ETF
volumes:
    etf_vol:
       driver: local

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: $SUBNET
         gateway: $GTW
